# Generated by Django 4.0.5 on 2022-08-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_attendancereport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancereport',
            old_name='status',
            new_name='coming_status',
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='coming_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='going_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancereport',
            name='going_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
