# Generated by Django 4.0.5 on 2022-08-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('entry', models.CharField(choices=[('N', 'New'), ('O', 'Old')], max_length=50)),
                ('semester', models.CharField(choices=[('ft', 'First Term'), ('st', 'Second Term'), ('tt', 'Third Term')], max_length=50)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('amount_in_words', models.CharField(blank=True, max_length=100, null=True)),
                ('due_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('fully_paid', models.BooleanField(default=False)),
                ('partly_paid', models.BooleanField(default=False)),
                ('date_paid', models.DateField(auto_now=True)),
                ('updated_paid_date', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.classroom')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'verbose_name': 'Fee',
                'verbose_name_plural': 'Fees',
            },
        ),
        migrations.CreateModel(
            name='ServicesTokenStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('token', models.CharField(max_length=650)),
                ('created_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='receipts')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fee')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineFeesOnProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(max_length=150)),
                ('token', models.CharField(blank=True, max_length=600, null=True)),
                ('entry', models.CharField(choices=[('N', 'New'), ('O', 'Old')], max_length=50)),
                ('semester', models.CharField(choices=[('ft', 'First Term'), ('st', 'Second Term'), ('tt', 'Third Term')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.BooleanField(default=False)),
                ('amount_in_words', models.CharField(blank=True, max_length=100, null=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.classroom')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
