# Generated by Django 4.0.5 on 2022-08-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='semester',
            field=models.CharField(choices=[('ft', 'First Trimester'), ('st', 'Second Trimester'), ('tt', 'Third Trimester')], max_length=50),
        ),
        migrations.AlterField(
            model_name='onlinefeesonprogress',
            name='semester',
            field=models.CharField(choices=[('ft', 'First Trimester'), ('st', 'Second Trimester'), ('tt', 'Third Trimester')], max_length=50),
        ),
    ]
