# Generated by Django 4.0.5 on 2022-08-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0003_rename_status_attendancereport_coming_status_and_more'),
        ('student', '0007_studentgovernment_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classroom')),
                ('department_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.staff')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
            options={
                'verbose_name': 'TimeTable',
                'verbose_name_plural': 'TimeTables',
                'unique_together': {('staff_id', 'class_id', 'subject_id', 'start_time', 'end_time')},
            },
        ),
    ]
