# Generated by Django 4.0.5 on 2022-08-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentgovernment_created_at'),
        ('teacher', '0003_rename_status_attendancereport_coming_status_and_more'),
        ('timetable', '0002_timetable_day'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=1, max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('staff_id', 'class_id', 'day', 'subject_id', 'start_time', 'end_time')},
        ),
    ]
