# Generated by Django 4.0.5 on 2022-08-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_finaltimetable_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaltimetable',
            name='day',
            field=models.CharField(choices=[('Mon', 'Monday'), ('Tues', 'Tuesday'), ('Wed', 'Wednesday'), ('Thurs', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default=1, max_length=6),
        ),
    ]
