# Generated by Django 4.0.5 on 2022-08-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='children',
            field=models.ManyToManyField(related_name='student', to='student.student'),
        ),
    ]
