# Generated by Django 4.0.5 on 2022-08-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_guardian_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgovernment',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
