# Generated by Django 4.0.5 on 2022-08-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_studentgovernment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='guardian_profile_picture',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/default.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
