# Generated by Django 4.0.5 on 2023-08-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_admission_guardian_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='entry',
            field=models.CharField(choices=[('N', 'New'), ('O', 'Old')], default=('N', 'New'), max_length=116),
        ),
    ]
