# Generated by Django 4.0.5 on 2022-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('1', 'HOD'), ('2', 'Staff'), ('3', 'Student'), ('4', 'Guardian')], max_length=15, null=True),
        ),
    ]
