# Generated by Django 4.0.5 on 2022-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='home_work',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='home_work_overall',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='project',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='mark',
            name='project_overall',
            field=models.IntegerField(blank=True, default=20, null=True),
        ),
    ]
