# Generated by Django 4.0.5 on 2022-09-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_mark_home_work_mark_home_work_overall_mark_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='exam_overall',
            new_name='exam_on',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='home_work_overall',
            new_name='home_work_on',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='project_overall',
            new_name='project_on',
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='test_overall',
            new_name='test_on',
        ),
    ]
