# Generated by Django 4.0.5 on 2022-09-29 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_admission_guardian_profile_picture_and_more'),
        ('marks', '0003_rename_exam_overall_mark_exam_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('Jun', 'Jun'), ('Jul', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'november'), ('Dec', 'December')], default='Sep', max_length=10),
        ),
        migrations.AlterField(
            model_name='mark',
            name='semester',
            field=models.CharField(choices=[('ft', 'first term'), ('st', 'second term'), ('tt', 'third term')], max_length=10),
        ),
        migrations.CreateModel(
            name='StudentAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('ft', 'first term'), ('st', 'second term'), ('tt', 'third term')], max_length=50)),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_id_average', to='student.classroom')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_average', to='student.student')),
            ],
            options={
                'verbose_name': 'StudentAverage',
                'verbose_name_plural': 'StudentAverages',
            },
        ),
    ]
