# Generated by Django 4.0.5 on 2022-10-05 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_admission_guardian_profile_picture_and_more'),
        ('marks', '0004_mark_month_alter_mark_semester_studentaverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='semester',
            field=models.CharField(choices=[('ft', 'first Trimester'), ('st', 'second Trimester'), ('tt', 'third Trimester')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentaverage',
            name='semester',
            field=models.CharField(choices=[('ft', 'first Trimester'), ('st', 'second Trimester'), ('tt', 'third Trimester')], max_length=50),
        ),
        migrations.CreateModel(
            name='StudentSubjectAverageGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('ft', 'first Trimester'), ('st', 'second Trimester'), ('tt', 'third Trimester')], max_length=50)),
                ('average', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('grade', models.CharField(max_length=3)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_id_grade', to='student.classroom')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_id_grade', to='student.student')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_id_grade', to='student.subject')),
            ],
            options={
                'verbose_name': 'StudentSubjectAverageGrad',
                'verbose_name_plural': 'StudentSubjectAverageGrads',
            },
        ),
        migrations.AddField(
            model_name='studentaverage',
            name='subjects_grads',
            field=models.ManyToManyField(to='marks.studentsubjectaveragegrade', verbose_name='subjects_grade'),
        ),
    ]
