# Generated by Django 4.0.5 on 2022-08-11 09:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('school_name_full', models.CharField(blank=True, max_length=350, null=True)),
                ('address', models.CharField(max_length=350)),
                ('email', models.CharField(max_length=350)),
                ('phone', models.CharField(max_length=350)),
                ('fee_phone', models.CharField(blank=True, max_length=350, null=True)),
                ('whatsApp', models.CharField(max_length=350)),
                ('website', models.CharField(max_length=350)),
                ('new_student_fee', models.FloatField(default=0.0)),
                ('old_student_fee', models.FloatField(default=0.0)),
                ('school_logo', models.ImageField(upload_to='logo')),
                ('school_banner_image', models.ImageField(blank=True, default='images/banner.png', null=True, upload_to='banner')),
                ('motto', models.CharField(max_length=350)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('history', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('region', models.CharField(max_length=350)),
                ('town', models.CharField(max_length=350)),
                ('po_box', models.CharField(max_length=350)),
            ],
            options={
                'verbose_name': 'SchoolInformation',
                'verbose_name_plural': "Schoolinformation's",
            },
        ),
    ]
