# Generated by Django 4.0.5 on 2022-08-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0002_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_logo',
            field=models.ImageField(max_length=500, upload_to='logo'),
        ),
    ]
