# Generated by Django 4.0.5 on 2022-08-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0003_alter_schoolinformation_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='h_o_s_signature',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='signature'),
        ),
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_banner_image',
            field=models.ImageField(blank=True, default='images/banner.png', max_length=500, null=True, upload_to='banner'),
        ),
    ]
