# Generated by Django 4.0.5 on 2022-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0004_schoolinformation_h_o_s_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='school_stamp',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='signature'),
        ),
    ]
