# Generated by Django 4.0.5 on 2022-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolinfo', '0006_alter_schoolinformation_school_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolinformation',
            name='school_stamp',
            field=models.ImageField(blank=True, default='images/banner.png', max_length=500, null=True, upload_to='stamp'),
        ),
    ]
